### ISSUE TITLE
A "/ var/www/vendor does not exist and could not be created" error occurred when the gpw-web container started

### ISSUE THREAD

**Issue by asdmailwl** [Mosasauroidea/GazellePW#40] opened 2022-11-23 13:13 UTC
gpw-web            | Composer version 2.4.4 2022-10-27 14:39:29
gpw-web            | Installing dependencies from lock file (including require-dev)
gpw-web            | Verifying lock file contents can be installed on current platform.
gpw-web            | Package operations: 88 installs, 0 updates, 0 removals
gpw-web            | 
gpw-web            | In Filesystem.php line 254:
gpw-web            |                                                             
gpw-web            |   /var/www/vendor does not exist and could not be created.  
gpw-web            |                                                             
gpw-web            | 
gpw-web            | install [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-progress] [--no-install] [--audit] [--audit-format AUDIT-FORMAT] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>...]
gpw-web            | 
gpw-web            | 
gpw-web            | ====== Yarn Install ======
gpw-web            | yarn install v1.22.19
gpw-web            | [1/4] Resolving packages...
gpw-web            | success Already up-to-date.
gpw-web            | Done in 1.46s.
gpw-web            | 
gpw-web            | ====== Yarn Start ======
gpw-web            | Run migrations...
gpw-web            | /var/www/.docker/web/entrypoint.sh: line 30: /var/www/vendor/bin/phinx: No such file or directory
gpw-web            | PHINX FAILED TO RUN MIGRATIONS
gpw-web exited with code 1
gpw-manticoresearch | Still waiting for Web (Count: 100).
gpw-manticoresearch | Still waiting for Web (Count: 120).
gpw-manticoresearch | Still waiting for Web (Count: 140).
gpw-manticoresearch | Still waiting for Web (Count: 160).
gpw-manticoresearch | Still waiting for Web (Count: 180).
gpw-manticoresearch | Still waiting for Web (Count: 200).

**Comment by 120318** [comment] 2022-12-05 09:20
Duplicate of #2

**Closed as completed by 120318** 2022-12-05 09:20 UTC
